/** @type {import('tailwindcss').Config} */
// eslint-disable-next-line no-undef
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        text: {
          0: '#463b2d',
          50: '#f5f3ef',
          100: '#ebe6e0',
          200: '#d7cdc1',
          300: '#c3b5a2',
          400: '#af9c83',
          500: '#9c8363',
          600: '#7c6950',
          700: '#5d4f3c',
          800: '#3e3428',
          900: '#1f1a14',
          950: '#100d0a',
        },
        bgcolor: {
          0: '#FCFAF6',
          50: '#f7f4ed',
          100: '#efe9dc',
          200: '#dfd4b9',
          300: '#d0be95',
          400: '#c0a972',
          500: '#b0934f',
          600: '#8d763f',
          700: '#6a582f',
          800: '#463b20',
          900: '#231d10',
          950: '#120f08',
        },
        primary: {
          0: '#43766C',
          50: '#eff6f4',
          100: '#deedea',
          200: '#bedad5',
          300: '#9dc8bf',
          400: '#7cb6aa',
          500: '#5ca395',
          600: '#498377',
          700: '#376259',
          800: '#25413c',
          900: '#12211e',
          950: '#09100f',
        },
        secondary: {
          0: '#F8FAE5',
          50: '#f9fbea',
          100: '#f3f7d4',
          200: '#e8efa9',
          300: '#dce77e',
          400: '#d0de54',
          500: '#c5d629',
          600: '#9dab21',
          700: '#768118',
          800: '#4f5610',
          900: '#272b08',
          950: '#141504',
        },
        accent: {
          0: '#76453B',
          50: '#f6efee',
          100: '#eee0dd',
          200: '#ddc1bb',
          300: '#cca299',
          400: '#bb8377',
          500: '#aa6355',
          600: '#885044',
          700: '#663c33',
          800: '#442822',
          900: '#221411',
          950: '#110a09',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        // primary: {
        //   DEFAULT: "hsl(var(--primary))",
        //   foreground: "hsl(var(--primary-foreground))",
        // },
        // secondary: {
        //   DEFAULT: "hsl(var(--secondary))",
        //   foreground: "hsl(var(--secondary-foreground))",
        // },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        // accent: {
        //   DEFAULT: "hsl(var(--accent))",
        //   foreground: "hsl(var(--accent-foreground))",
        // },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  // eslint-disable-next-line no-undef
  plugins: [require('tailwindcss-animate')],
};
